[lint]
select = [
    "A",
    "ARG",
    "ASYNC",
    "B",
    "C",
    "DTZ",
    "E",
    "ERA",
    "EXE",
    "F",
    "FLY",
    "I",
    "ICN",
    "INP",
    "NPY",
    "PIE",
    "PL",
    "PT",
    "PTH",
    "PYI",
    "RSE",
    "RUF",
    "SIM",
    "SLF",
    "TD",
    "TID",
    "UP",
    "W",
    "YTT",
]
ignore = [
    "D203",
    "TD002",
    "TD003",
    "PGH003",
    "F841",
    "E501",
    "E712",
    "PLR0913",
    "C901",
    "PLR2004",
]
fixable = ["ALL"]
